version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: r0ot@31
      MONGO_INITDB_DATABASE: vfsimplesigning
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: "1"
      FLASK_ENV: "development"
      MONGO_URI: "mongodb://root:r0ot@31@mongodb/vfsimplesigning"
    depends_on:
      - mongodb

volumes:
  mongodb-data: